package ioc.colectllibre.layout;

import ioc.colectllibre.model.Usuari;
import ioc.colectllibre.util.Data;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 * @author Rubén
 * 
 * Classe que hereta de JFrame i es mostra un cop un usuari ha fet login
 * correctament.
 */
public class Frame_menu extends javax.swing.JFrame {
    
    private Usuari currentUser;
    
    public Frame_menu(Usuari currentUser) {
	initComponents();
	this.setLocationRelativeTo(null);
	this.setTitle("ColectLlibres");
	this.currentUser = currentUser;
	
	// Iniciar panels
	jPanel_inici = new Panel_inici(currentUser.getNomUsuari());
	jPanel_account = new Panel_account(currentUser);
	
	// TODO Comprovar si l'usuari és administrador
	jPanel_users = new Panel_usuaris();
	/*
	if (currentUser.isAdmin()) {
	    jButton_userTable.setVisible(true);
	    jPanel_users = new Panel_usuaris();
	} else {
	    jButton_userTable.setVisible(false);
	}
	*/
	// Mostrar panel inici
	jPanel_parent.removeAll();
	jPanel_parent.add(jPanel_inici);
	jPanel_parent.repaint();
	jPanel_parent.revalidate();
	
	// Afegir listeners als botons del dashboard
	ButtonHover hover = new ButtonHover();
	jButton_inici.addMouseListener(hover);
	jButton_bookList.addMouseListener(hover);
	jButton_userTable.addMouseListener(hover);
	jButton_account.addMouseListener(hover);
	jButton_logout.addMouseListener(hover);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_dashboard = new javax.swing.JPanel();
        jButton_logout = new javax.swing.JButton();
        jButton_inici = new javax.swing.JButton();
        jButton_bookList = new javax.swing.JButton();
        jButton_userTable = new javax.swing.JButton();
        jButton_account = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel_parent = new javax.swing.JPanel();
        jPanel_inici = new javax.swing.JPanel();
        jPanel_account = new javax.swing.JPanel();
        jPanel_users = new javax.swing.JPanel();
        jPanel_booklist = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(39, 40, 37));

        jPanel_dashboard.setBackground(new java.awt.Color(241, 241, 244));
        jPanel_dashboard.setForeground(new java.awt.Color(220, 222, 222));

        jButton_logout.setBackground(new java.awt.Color(241, 241, 244));
        jButton_logout.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton_logout.setForeground(new java.awt.Color(51, 51, 51));
        jButton_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_logout_rounded_left_30px.png"))); // NOI18N
        jButton_logout.setText("Tancar sessió");
        jButton_logout.setToolTipText("Tancar sessió");
        jButton_logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        jButton_inici.setBackground(new java.awt.Color(241, 241, 244));
        jButton_inici.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton_inici.setForeground(new java.awt.Color(51, 51, 51));
        jButton_inici.setText("Inici");
        jButton_inici.setBorder(null);
        jButton_inici.setPreferredSize(new java.awt.Dimension(149, 30));
        jButton_inici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iniciActionPerformed(evt);
            }
        });

        jButton_bookList.setBackground(new java.awt.Color(241, 241, 244));
        jButton_bookList.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton_bookList.setForeground(new java.awt.Color(51, 51, 51));
        jButton_bookList.setText("Llistat llibres");
        jButton_bookList.setBorder(null);
        jButton_bookList.setPreferredSize(new java.awt.Dimension(149, 30));
        jButton_bookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bookListActionPerformed(evt);
            }
        });

        jButton_userTable.setBackground(new java.awt.Color(241, 241, 244));
        jButton_userTable.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton_userTable.setForeground(new java.awt.Color(51, 51, 51));
        jButton_userTable.setText("Taula usuaris");
        jButton_userTable.setBorder(null);
        jButton_userTable.setPreferredSize(new java.awt.Dimension(149, 30));
        jButton_userTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_userTableActionPerformed(evt);
            }
        });

        jButton_account.setBackground(new java.awt.Color(241, 241, 244));
        jButton_account.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton_account.setForeground(new java.awt.Color(51, 51, 51));
        jButton_account.setText("El meu compte");
        jButton_account.setBorder(null);
        jButton_account.setPreferredSize(new java.awt.Dimension(149, 30));
        jButton_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_accountActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colectllibres_black100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_dashboardLayout = new javax.swing.GroupLayout(jPanel_dashboard);
        jPanel_dashboard.setLayout(jPanel_dashboardLayout);
        jPanel_dashboardLayout.setHorizontalGroup(
            jPanel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_bookList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_inici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jButton_userTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_dashboardLayout.setVerticalGroup(
            jPanel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_inici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_bookList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_userTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(jButton_logout)
                .addContainerGap())
        );

        getContentPane().add(jPanel_dashboard, java.awt.BorderLayout.LINE_START);

        jPanel_parent.setLayout(new java.awt.CardLayout());

        jPanel_inici.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_iniciLayout = new javax.swing.GroupLayout(jPanel_inici);
        jPanel_inici.setLayout(jPanel_iniciLayout);
        jPanel_iniciLayout.setHorizontalGroup(
            jPanel_iniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        jPanel_iniciLayout.setVerticalGroup(
            jPanel_iniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jPanel_parent.add(jPanel_inici, "card4");

        javax.swing.GroupLayout jPanel_accountLayout = new javax.swing.GroupLayout(jPanel_account);
        jPanel_account.setLayout(jPanel_accountLayout);
        jPanel_accountLayout.setHorizontalGroup(
            jPanel_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        jPanel_accountLayout.setVerticalGroup(
            jPanel_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jPanel_parent.add(jPanel_account, "card2");

        jPanel_users.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_usersLayout = new javax.swing.GroupLayout(jPanel_users);
        jPanel_users.setLayout(jPanel_usersLayout);
        jPanel_usersLayout.setHorizontalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        jPanel_usersLayout.setVerticalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jPanel_parent.add(jPanel_users, "card3");

        javax.swing.GroupLayout jPanel_booklistLayout = new javax.swing.GroupLayout(jPanel_booklist);
        jPanel_booklist.setLayout(jPanel_booklistLayout);
        jPanel_booklistLayout.setHorizontalGroup(
            jPanel_booklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        jPanel_booklistLayout.setVerticalGroup(
            jPanel_booklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jPanel_parent.add(jPanel_booklist, "card5");

        getContentPane().add(jPanel_parent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Fa logout i torna a la pantalla de Login
     * 
     * @param evt 
     */
    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
	this.dispose();
	new Frame_login().setVisible(true);
    }//GEN-LAST:event_jButton_logoutActionPerformed
    
    /**
     * Canvia el JPanel que es mostra al CardLayout (jPanel_welcome) 
     * 
     * @param evt 
     */
    private void jButton_iniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iniciActionPerformed
        jPanel_parent.removeAll();
	jPanel_parent.add(jPanel_inici);
	jPanel_parent.repaint();
	jPanel_parent.revalidate();
    }//GEN-LAST:event_jButton_iniciActionPerformed
    
    /**
     * TODO
     * 
     * @param evt 
     */
    private void jButton_bookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bookListActionPerformed
    }//GEN-LAST:event_jButton_bookListActionPerformed
    
    /**
     * Canvia el JPanel que es mostra al CardLayout (jPanel_userList) 
     * 
     * @param evt 
     */
    private void jButton_userTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_userTableActionPerformed
        jPanel_parent.removeAll();
	jPanel_parent.add(jPanel_users);
	jPanel_parent.repaint();
	jPanel_parent.revalidate();
    }//GEN-LAST:event_jButton_userTableActionPerformed
    
    /**
     * Canvia el JPanel que es mostra al CardLayout (jPanel_account) 
     * 
     * @param evt 
     */
    private void jButton_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_accountActionPerformed
	jPanel_parent.removeAll();
	jPanel_parent.add(jPanel_account);
	jPanel_parent.repaint();
	jPanel_parent.revalidate();
    }//GEN-LAST:event_jButton_accountActionPerformed
    
    /**
     * Classe interna que implemeneta un MouseListener per afegir a tots els 
     * botons del dashboard.
     */
    class ButtonHover implements MouseListener {

	@Override
	public void mouseClicked(MouseEvent e) {}

	@Override
	public void mousePressed(MouseEvent e) {}

	@Override
	public void mouseReleased(MouseEvent e) {}

	@Override
	public void mouseEntered(MouseEvent e) {
	    JButton jb = (JButton) e.getSource();
	    jb.setBackground(Data.BUTTON_HOVER);
	}

	@Override
	public void mouseExited(MouseEvent e) {
	    JButton jb = (JButton) e.getSource();
	    jb.setBackground(Data.BUTTON);
	}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_account;
    private javax.swing.JButton jButton_bookList;
    private javax.swing.JButton jButton_inici;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_userTable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_account;
    private javax.swing.JPanel jPanel_booklist;
    private javax.swing.JPanel jPanel_dashboard;
    private javax.swing.JPanel jPanel_inici;
    private javax.swing.JPanel jPanel_parent;
    private javax.swing.JPanel jPanel_users;
    // End of variables declaration//GEN-END:variables
}
