package ioc.colectllibre.layout;

import ioc.colectllibre.util.Util_XML;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JMenuBar;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 * @author Rubén
 * 
 * Classe que hereta de JFrame i es mostra un cop un usuari ha fet login
 * correctament.
 */
public class MenuForm extends javax.swing.JFrame {

    private String[][] info_Usuaris;
    private DefaultTableModel model;

    public MenuForm() {
	initComponents();
	this.setLocationRelativeTo(null);
	omplirTaulaUsuaris();
	
	// Afegir listeners als botons del dashboard
	ButtonHover hover = new ButtonHover();
	jButton_inici.addMouseListener(hover);
	jButton_bookList.addMouseListener(hover);
	jButton_userTable.addMouseListener(hover);
	jButton_logout.addMouseListener(hover);
	jButton_account.addMouseListener(hover);
    }

    /**
     * Omple la taula a partir d'una petició al servidor que retorna un arxiu 
     * XML amb totes les dades dels usuaris a la base de dades.
     */
    public void omplirTaulaUsuaris() {

	info_Usuaris = Util_XML.getInfoUsuaris();
	model = (DefaultTableModel) jTable_usuaris.getModel();

	model.setRowCount(0);

	for (int i = 0; i < info_Usuaris.length; i++) {
	    String[] row = new String[info_Usuaris[i].length];
	    for (int j = 0; j < info_Usuaris[i].length; j++) {
		row[j] = info_Usuaris[i][j];
	    }
	    model.addRow(row);
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_dashboard = new javax.swing.JPanel();
        jButton_logout = new javax.swing.JButton();
        jButton_inici = new javax.swing.JButton();
        jButton_bookList = new javax.swing.JButton();
        jButton_userTable = new javax.swing.JButton();
        jButton_account = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel_parent = new javax.swing.JPanel();
        jPanel_welcome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_account = new javax.swing.JPanel();
        jPanel_userList = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_usuaris = new javax.swing.JTable();
        jTextField_filter = new javax.swing.JTextField();
        jLabel_search = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(39, 40, 37));

        jPanel_dashboard.setBackground(new java.awt.Color(241, 241, 244));
        jPanel_dashboard.setForeground(new java.awt.Color(220, 222, 222));

        jButton_logout.setBackground(new java.awt.Color(241, 241, 244));
        jButton_logout.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton_logout.setForeground(new java.awt.Color(51, 51, 51));
        jButton_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_logout_rounded_left_30px.png"))); // NOI18N
        jButton_logout.setText("Tancar sessió");
        jButton_logout.setToolTipText("Tancar sessió");
        jButton_logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        jButton_inici.setBackground(new java.awt.Color(241, 241, 244));
        jButton_inici.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton_inici.setForeground(new java.awt.Color(51, 51, 51));
        jButton_inici.setText("Inici");
        jButton_inici.setBorder(null);
        jButton_inici.setPreferredSize(new java.awt.Dimension(149, 30));
        jButton_inici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iniciActionPerformed(evt);
            }
        });

        jButton_bookList.setBackground(new java.awt.Color(241, 241, 244));
        jButton_bookList.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton_bookList.setForeground(new java.awt.Color(51, 51, 51));
        jButton_bookList.setText("Llistat llibres");
        jButton_bookList.setBorder(null);
        jButton_bookList.setPreferredSize(new java.awt.Dimension(149, 30));
        jButton_bookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bookListActionPerformed(evt);
            }
        });

        jButton_userTable.setBackground(new java.awt.Color(241, 241, 244));
        jButton_userTable.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton_userTable.setForeground(new java.awt.Color(51, 51, 51));
        jButton_userTable.setText("Taula usuaris");
        jButton_userTable.setBorder(null);
        jButton_userTable.setPreferredSize(new java.awt.Dimension(149, 30));
        jButton_userTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_userTableActionPerformed(evt);
            }
        });

        jButton_account.setBackground(new java.awt.Color(241, 241, 244));
        jButton_account.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton_account.setForeground(new java.awt.Color(51, 51, 51));
        jButton_account.setText("El meu compte");
        jButton_account.setBorder(null);
        jButton_account.setPreferredSize(new java.awt.Dimension(149, 30));
        jButton_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_accountActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colectllibres_black100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_dashboardLayout = new javax.swing.GroupLayout(jPanel_dashboard);
        jPanel_dashboard.setLayout(jPanel_dashboardLayout);
        jPanel_dashboardLayout.setHorizontalGroup(
            jPanel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_bookList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_inici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jButton_userTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_dashboardLayout.setVerticalGroup(
            jPanel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_inici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_bookList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_userTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(jButton_logout)
                .addContainerGap())
        );

        getContentPane().add(jPanel_dashboard, java.awt.BorderLayout.LINE_START);

        jPanel_parent.setLayout(new java.awt.CardLayout());

        jPanel_welcome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Benvingut/da a Colectllibres!");

        javax.swing.GroupLayout jPanel_welcomeLayout = new javax.swing.GroupLayout(jPanel_welcome);
        jPanel_welcome.setLayout(jPanel_welcomeLayout);
        jPanel_welcomeLayout.setHorizontalGroup(
            jPanel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_welcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_welcomeLayout.setVerticalGroup(
            jPanel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_welcomeLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        jPanel_parent.add(jPanel_welcome, "card4");

        javax.swing.GroupLayout jPanel_accountLayout = new javax.swing.GroupLayout(jPanel_account);
        jPanel_account.setLayout(jPanel_accountLayout);
        jPanel_accountLayout.setHorizontalGroup(
            jPanel_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        jPanel_accountLayout.setVerticalGroup(
            jPanel_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jPanel_parent.add(jPanel_account, "card2");

        jPanel_userList.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(39, 40, 37));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAULA D'USUARIS REGISTRATS");

        jTable_usuaris.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTable_usuaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOM", "COGNOMS", "TELEFON", "DNI", "USUARI", "CONTRASSENYA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_usuaris.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_usuaris);

        jTextField_filter.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_filter.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jTextField_filter.setForeground(new java.awt.Color(39, 40, 37));
        jTextField_filter.setText("Cerca per id, nom, cognoms...");
        jTextField_filter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_filter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_filterMouseClicked(evt);
            }
        });
        jTextField_filter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_filterKeyReleased(evt);
            }
        });

        jLabel_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_userListLayout = new javax.swing.GroupLayout(jPanel_userList);
        jPanel_userList.setLayout(jPanel_userListLayout);
        jPanel_userListLayout.setHorizontalGroup(
            jPanel_userListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_userListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_userListLayout.createSequentialGroup()
                        .addComponent(jLabel_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_filter))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_userListLayout.setVerticalGroup(
            jPanel_userListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_userListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_filter))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        jPanel_parent.add(jPanel_userList, "card3");

        getContentPane().add(jPanel_parent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Fa logout i torna a la pantalla de Login
     * 
     * @param evt 
     */
    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
	this.dispose();
	new LoginForm().setVisible(true);
    }//GEN-LAST:event_jButton_logoutActionPerformed
    
    /**
     * Canvia el JPanel que es mostra al CardLayout (jPanel_welcome) 
     * 
     * @param evt 
     */
    private void jButton_iniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iniciActionPerformed
        jPanel_parent.removeAll();
	jPanel_parent.add(jPanel_welcome);
	jPanel_parent.repaint();
	jPanel_parent.revalidate();
    }//GEN-LAST:event_jButton_iniciActionPerformed
    
    /**
     * TODO
     * 
     * @param evt 
     */
    private void jButton_bookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bookListActionPerformed
    }//GEN-LAST:event_jButton_bookListActionPerformed
    
    /**
     * Canvia el JPanel que es mostra al CardLayout (jPanel_userList) 
     * 
     * @param evt 
     */
    private void jButton_userTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_userTableActionPerformed
        jPanel_parent.removeAll();
	jPanel_parent.add(jPanel_userList);
	jPanel_parent.repaint();
	jPanel_parent.revalidate();
    }//GEN-LAST:event_jButton_userTableActionPerformed
    
    /**
     * Esdeveniment que en fer clic al jTextField, es selecciona tot el text.
     * 
     * @param evt 
     */
    private void jTextField_filterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_filterMouseClicked
	jTextField_filter.selectAll();
    }//GEN-LAST:event_jTextField_filterMouseClicked
    
    /**
     * Esdeveniment que detecta quan es pitja una tecla en el jTextField i crida
     * el métode per filtrar la taula.
     * 
     * @param evt 
     */
    private void jTextField_filterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_filterKeyReleased
        filter(jTextField_filter.getText());
    }//GEN-LAST:event_jTextField_filterKeyReleased

    private void jButton_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_accountActionPerformed
    
    /**
     * Classe interna que implemeneta un MouseListener per afegir a tots els 
     * botons del dashboard.
     */
    class ButtonHover implements MouseListener {

	@Override
	public void mouseClicked(MouseEvent e) {}

	@Override
	public void mousePressed(MouseEvent e) {}

	@Override
	public void mouseReleased(MouseEvent e) {}

	@Override
	public void mouseEntered(MouseEvent e) {
	    JButton jb = (JButton) e.getSource();
	    jb.setBackground(new Color(204,204,204));
	}

	@Override
	public void mouseExited(MouseEvent e) {
	    JButton jb = (JButton) e.getSource();
	    jb.setBackground(new Color(241,241,244));
	}
    }

    @Override
    public JMenuBar getJMenuBar() {
	return super.getJMenuBar(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setJMenuBar(JMenuBar menubar) {
	super.setJMenuBar(menubar); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * Métode que filtra les dades de la jTable a partir del text introduit per
     * l'usuari, s'actualitza de manera dinàmica.
     * 
     * @param query = text introduit per l'usuari
     */
    public void filter(String query) {
	TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
	jTable_usuaris.setRowSorter(sorter);
	sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_account;
    private javax.swing.JButton jButton_bookList;
    private javax.swing.JButton jButton_inici;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_userTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_search;
    private javax.swing.JPanel jPanel_account;
    private javax.swing.JPanel jPanel_dashboard;
    private javax.swing.JPanel jPanel_parent;
    private javax.swing.JPanel jPanel_userList;
    private javax.swing.JPanel jPanel_welcome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_usuaris;
    private javax.swing.JTextField jTextField_filter;
    // End of variables declaration//GEN-END:variables
}
