package ioc.colectllibre.layout;

import ioc.colectllibre.model.Usuari;
import ioc.colectllibre.util.Connection;
import ioc.colectllibre.util.Data;
import java.util.Arrays;

/**
 * @author Rubén
 */
public class Panel_account extends javax.swing.JPanel {
    
    private Usuari currentUser;
    
    public Panel_account(Usuari currentUser) {
	initComponents();
	this.currentUser = currentUser;
	
	// Visibilitat inicial dels components
	jLabel_novaContrasenya.setVisible(false);
	jLabel_repNovaContrasenya.setVisible(false);
	jPasswordField_novaContrasenya.setVisible(false);
	jPasswordField_repNovaContrasenya.setVisible(false);
	jButton_canviarContrasenya.setVisible(false);
	jLabel_canviarContrasenya.setVisible(false);
	
	// Els camps per defecte no es poden editar
	jTextField_nom.setEditable(false);
	jTextField_cognoms.setEditable(false);
	jTextField_dni.setEditable(false);
	jTextField_telefon.setEditable(false);
	jTextField_nomUsuari.setEditable(false);
	jPasswordField_contrassenya.setEditable(false);
	
	// Text per defecte als camps de text
	jTextField_nom.setText(currentUser.getNom());
	jTextField_cognoms.setText(currentUser.getCognoms());
	jTextField_dni.setText(currentUser.getDni());
	jTextField_telefon.setText(currentUser.getTelefon());
	jTextField_nomUsuari.setText(currentUser.getNomUsuari());
	jPasswordField_contrassenya.setText(currentUser.getContrasenya());
	
	// Disseny camps de text
	jTextField_nom.setBorder(Data.BORDER);
	jTextField_cognoms.setBorder(Data.BORDER);
	jTextField_dni.setBorder(Data.BORDER);
	jTextField_telefon.setBorder(Data.BORDER);
	jTextField_nomUsuari.setBorder(Data.BORDER);
	jPasswordField_contrassenya.setBorder(Data.BORDER);
	jPasswordField_novaContrasenya.setBorder(Data.BORDER);
	jPasswordField_repNovaContrasenya.setBorder(Data.BORDER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_nom = new javax.swing.JTextField();
        jTextField_cognoms = new javax.swing.JTextField();
        jTextField_telefon = new javax.swing.JTextField();
        jTextField_dni = new javax.swing.JTextField();
        jTextField_nomUsuari = new javax.swing.JTextField();
        jPasswordField_contrassenya = new javax.swing.JPasswordField();
        jLabel_novaContrasenya = new javax.swing.JLabel();
        jLabel_repNovaContrasenya = new javax.swing.JLabel();
        jPasswordField_novaContrasenya = new javax.swing.JPasswordField();
        jPasswordField_repNovaContrasenya = new javax.swing.JPasswordField();
        jButton_canviarContrasenya = new javax.swing.JButton();
        jLabel_canviarContrasenya = new javax.swing.JLabel();
        label_info = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(741, 551));

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 40, 37));
        jLabel2.setText("Nom");

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 40, 37));
        jLabel3.setText("Cognoms");

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 40, 37));
        jLabel4.setText("Telèfon");

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(39, 40, 37));
        jLabel8.setText("DNI");

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 40, 37));
        jLabel5.setText("Nom d'usuari");

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 40, 37));
        jLabel6.setText("Contrasenya");

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(39, 40, 37));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORMACIÓ PERSONAL");

        jTextField_nom.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_nom.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField_nom.setForeground(new java.awt.Color(0, 0, 0));

        jTextField_cognoms.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_cognoms.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField_cognoms.setForeground(new java.awt.Color(0, 0, 0));

        jTextField_telefon.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_telefon.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField_telefon.setForeground(new java.awt.Color(0, 0, 0));

        jTextField_dni.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_dni.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField_dni.setForeground(new java.awt.Color(0, 0, 0));

        jTextField_nomUsuari.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_nomUsuari.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTextField_nomUsuari.setForeground(new java.awt.Color(0, 0, 0));

        jPasswordField_contrassenya.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField_contrassenya.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jPasswordField_contrassenya.setForeground(new java.awt.Color(0, 0, 0));

        jLabel_novaContrasenya.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel_novaContrasenya.setForeground(new java.awt.Color(39, 40, 37));
        jLabel_novaContrasenya.setText("Introdueix la nova contrasenya");

        jLabel_repNovaContrasenya.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel_repNovaContrasenya.setForeground(new java.awt.Color(39, 40, 37));
        jLabel_repNovaContrasenya.setText("Repeteix la nova contrasenya");

        jPasswordField_novaContrasenya.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField_novaContrasenya.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jPasswordField_novaContrasenya.setForeground(new java.awt.Color(0, 0, 0));

        jPasswordField_repNovaContrasenya.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField_repNovaContrasenya.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jPasswordField_repNovaContrasenya.setForeground(new java.awt.Color(0, 0, 0));

        jButton_canviarContrasenya.setBackground(new java.awt.Color(51, 51, 51));
        jButton_canviarContrasenya.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jButton_canviarContrasenya.setForeground(new java.awt.Color(255, 255, 255));
        jButton_canviarContrasenya.setText("Canviar contrasenya");
        jButton_canviarContrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_canviarContrasenyaActionPerformed(evt);
            }
        });

        jLabel_canviarContrasenya.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel_canviarContrasenya.setForeground(new java.awt.Color(39, 40, 37));
        jLabel_canviarContrasenya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_canviarContrasenya.setText("Canviar contrasenya");

        label_info.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        label_info.setForeground(new java.awt.Color(255, 51, 51));
        label_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_canviarContrasenya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_novaContrasenya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_repNovaContrasenya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField_novaContrasenya, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(jPasswordField_repNovaContrasenya)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_nomUsuari, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_dni, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_telefon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_cognoms, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField_contrassenya)
                            .addComponent(jTextField_nom)))
                    .addComponent(jButton_canviarContrasenya, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cognoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nomUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_contrassenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addComponent(jLabel_canviarContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_novaContrasenya)
                    .addComponent(jPasswordField_novaContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_repNovaContrasenya)
                    .addComponent(jPasswordField_repNovaContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_canviarContrasenya)
                .addGap(18, 18, 18)
                .addComponent(label_info, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_canviarContrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_canviarContrasenyaActionPerformed
        if (!Arrays.equals(jPasswordField_novaContrasenya.getPassword(), jPasswordField_repNovaContrasenya.getPassword())){
	    label_info.setForeground(Data.ERROR);
	    label_info.setText("Les contrasenyes han de coincidir.");
	    return;
	}
	
	int code = Connection.changePassword(currentUser, String.valueOf(jPasswordField_novaContrasenya.getPassword()));
	
	if (code == 1) {
	    label_info.setForeground(Data.CORRECT);
	    label_info.setText("S'ha canviat la contrasenya correctament!");
	}
	else if (code == 2) {
	    label_info.setForeground(Data.ERROR);
	    label_info.setText("No s'ha pogut canviar la contrasenya.");
	}
    }//GEN-LAST:event_jButton_canviarContrasenyaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_canviarContrasenya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_canviarContrasenya;
    private javax.swing.JLabel jLabel_novaContrasenya;
    private javax.swing.JLabel jLabel_repNovaContrasenya;
    private javax.swing.JPasswordField jPasswordField_contrassenya;
    private javax.swing.JPasswordField jPasswordField_novaContrasenya;
    private javax.swing.JPasswordField jPasswordField_repNovaContrasenya;
    private javax.swing.JTextField jTextField_cognoms;
    private javax.swing.JTextField jTextField_dni;
    private javax.swing.JTextField jTextField_nom;
    private javax.swing.JTextField jTextField_nomUsuari;
    private javax.swing.JTextField jTextField_telefon;
    private javax.swing.JLabel label_info;
    // End of variables declaration//GEN-END:variables
}
