package ioc.colectllibre.layout;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 * @author Rubén
 * 
 * Classe per registrar usuaris a la base de dades
 */
public class Register_panel extends JPanel {
    
    private JFrame frame;
    private Login_panel loginPanel;
    
    public Register_panel(JFrame frame) {
	initComponents();
	this.frame = frame;
	frame.setSize(500, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        text_nom = new javax.swing.JTextField();
        text_telefon = new javax.swing.JTextField();
        text_nomUsuari = new javax.swing.JTextField();
        text_cognoms = new javax.swing.JTextField();
        button_registr = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        text_dni = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label_info = new javax.swing.JLabel();
        text_contrassenya = new javax.swing.JPasswordField();
        text_repContrassenya = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(39, 40, 37));
        jLabel1.setText("Nom:");

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 40, 37));
        jLabel2.setText("Cognoms:");

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 40, 37));
        jLabel3.setText("Telèfon:");

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 40, 37));
        jLabel4.setText("Nom d'usuari:");

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 40, 37));
        jLabel5.setText("Contrasenya:");

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 40, 37));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_registration_30px_1.png"))); // NOI18N
        jLabel6.setText(" Omple els camps següents per registrar-te:");

        jLabel7.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(39, 40, 37));
        jLabel7.setText("Repetir contrasenya:");

        text_nom.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        text_nom.setForeground(new java.awt.Color(39, 40, 37));
        text_nom.setPreferredSize(new java.awt.Dimension(184, 30));

        text_telefon.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        text_telefon.setForeground(new java.awt.Color(39, 40, 37));
        text_telefon.setPreferredSize(new java.awt.Dimension(184, 30));

        text_nomUsuari.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        text_nomUsuari.setForeground(new java.awt.Color(39, 40, 37));
        text_nomUsuari.setPreferredSize(new java.awt.Dimension(184, 30));

        text_cognoms.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        text_cognoms.setForeground(new java.awt.Color(39, 40, 37));
        text_cognoms.setPreferredSize(new java.awt.Dimension(184, 30));

        button_registr.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        button_registr.setForeground(new java.awt.Color(39, 40, 37));
        button_registr.setText("Registrar-se");
        button_registr.setMaximumSize(new java.awt.Dimension(95, 30));
        button_registr.setMinimumSize(new java.awt.Dimension(95, 30));
        button_registr.setPreferredSize(new java.awt.Dimension(95, 30));
        button_registr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registrActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(39, 40, 37));
        jLabel8.setText("DNI:");

        text_dni.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        text_dni.setForeground(new java.awt.Color(39, 40, 37));
        text_dni.setPreferredSize(new java.awt.Dimension(184, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_to_30px.png"))); // NOI18N
        jButton1.setToolTipText("Torna enrere");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label_info.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        label_info.setForeground(new java.awt.Color(255, 51, 51));
        label_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        text_contrassenya.setForeground(new java.awt.Color(39, 40, 37));
        text_contrassenya.setPreferredSize(new java.awt.Dimension(184, 30));

        text_repContrassenya.setForeground(new java.awt.Color(39, 40, 37));
        text_repContrassenya.setPreferredSize(new java.awt.Dimension(184, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_nomUsuari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_contrassenya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_repContrassenya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_registr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(118, 118, 118)
                        .addComponent(text_cognoms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(144, 144, 144)
                        .addComponent(text_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_telefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cognoms, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nomUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_contrassenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text_repContrassenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_registr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(label_info, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Botó registrar-se
    private void button_registrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registrActionPerformed
	
	// No poder haver-hi camps buits
	if (text_nom.getText().isEmpty() || text_cognoms.getText().isEmpty() || text_telefon.getText().isEmpty() ||
	    text_dni.getText().isEmpty() || text_nomUsuari.getText().isEmpty() || 
	    String.valueOf(text_contrassenya.getPassword()).isEmpty() || String.valueOf(text_repContrassenya.getSelectedText()).isEmpty())
	{
	    label_info.setText("Els camps no poden estar buits.");
	    return;
	}
	
	// Les contrasenyes han de coincidir
	if (String.valueOf(text_contrassenya.getPassword()) != String.valueOf(text_repContrassenya.getSelectedText())) {
	    label_info.setText("Les contrasenyes no coincideixen.");
	    return;
	}
	
	String[] credencials = new String[6];
	
	
	
    }//GEN-LAST:event_button_registrActionPerformed

    // Botó retornar (<)
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	
	loginPanel = new Login_panel(frame);
	
	JPanel parent = (JPanel) this.getParent();
	
	parent.removeAll();
	parent.add(loginPanel);
	parent.revalidate();
	parent.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_registr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_info;
    private javax.swing.JTextField text_cognoms;
    private javax.swing.JPasswordField text_contrassenya;
    private javax.swing.JTextField text_dni;
    private javax.swing.JTextField text_nom;
    private javax.swing.JTextField text_nomUsuari;
    private javax.swing.JPasswordField text_repContrassenya;
    private javax.swing.JTextField text_telefon;
    // End of variables declaration//GEN-END:variables
}
